# Generated by Django 5.2.7 on 2025-11-04 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categories_products_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brends')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='brends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brends'),
        ),
    ]
