# Generated by Django 5.2.7 on 2025-11-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brends_products_brends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brends',
            new_name='Brend',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brends',
            new_name='brend',
        ),
    ]
