# Generated by Django 5.2.7 on 2025-11-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_brends_brend_rename_categories_categorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brend',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
