# Generated by Django 5.2.7 on 2025-11-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_image_product_image1_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Нет описания', max_length=1500),
        ),
    ]
