# Generated by Django 5.2.7 on 2025-11-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(default=' ', max_length=1500),
            preserve_default=False,
        ),
    ]
